[redis_masters]
redis-node-1 ansible_host=127.0.0.1 ansible_port=2221
redis-node-2 ansible_host=127.0.0.1 ansible_port=2222
redis-node-3 ansible_host=127.0.0.1 ansible_port=2223

[redis_replicas]
redis-node-4 ansible_host=127.0.0.1 ansible_port=2224
redis-node-5 ansible_host=127.0.0.1 ansible_port=2225
redis-node-6 ansible_host=127.0.0.1 ansible_port=2226

[redis_all:children]
redis_masters
redis_replicas
