---
- name: Redis Cluster Status
  hosts: redis-node-1
  become: yes
  tasks:
    - name: Get cluster info
      command: /usr/local/bin/redis-cli -p 6379 cluster info
      register: cluster_info

    - name: Get cluster nodes
      command: /usr/local/bin/redis-cli -p 6379 cluster nodes
      register: cluster_nodes

    - name: Print cluster state
      debug:
        msg: "{{ cluster_info.stdout }}"

    - name: Print cluster nodes
      debug:
        msg: "{{ cluster_nodes.stdout }}"
